# This is a basic workflow to help you get started with Actions

name: ToPSGallery

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ master ]
  push:
    branches:
      - 'master'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    runs-on: ubuntu-latest
    environment: production
    steps:
        # Check out the main branch
      - uses: actions/checkout@master

      - name: Install the module
        run: |
          Write-Host $Env:GITHUB_REF
          $ModulePath = (Get-ChildItem -Path $(pwd).Path -Directory Ax*).FullName
          echo "MODULE_PATH=$ModulePath" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
          Write-Host "Path: $ModulePath"
          Import-Module $ModulePath
          Get-Module (Get-Item $ModulePath).Name
        shell: pwsh

      - name: Publish to Powershell Gallery
        run: |
          $ModulePath = $Env:MODULE_PATH
          Write-Host $ModulePath
          #Publish-Module -Name $ModulePath -NuGetApiKey "${{ secrets.PSGALLERYKEY }}"
        shell: pwsh