# This is a basic workflow to help you get started with Actions

name: ToPSGallery

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
        # Check out the main branch
      - uses: actions/checkout@main

      - name: Install the module
        run: |
          Write-Host $Env:GITHUB_REF
          $ModuleName = (Get-Item -Path $(pwd).Path).Name
          echo "MODULE_NAME=$ModuleName" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
          Write-Host "Path: $(pwd)"
          Import-Module $(pwd)
          Get-Module $ModuleName
        shell: pwsh

      - name: Publish to Powershell Gallery
        run: |
          Write-Host $Env:MODULE_NAME 
          # Publish-Module -Name $Env:MODULE_NAME -NuGetApiKey ${{ secrets.PSGALLERYKEY }}
          Get-Module $ModuleName
        shell: pwsh